const IGNORE_EXISTING = 'IGNORE_EXISTING'
const FAIL_IF_EXISTS = 'FAIL_IF_EXISTS'
const UPDATE_IF_EXISTS = 'UPDATE_IF_EXISTS'

export default {
  IGNORE_EXISTING,
  FAIL_IF_EXISTS,
  UPDATE_IF_EXISTS
}
