-- Migration from 193 to 194

CREATE DOMAIN EMAIL_VALUE AS VARCHAR(320);

ALTER DOMAIN USER_ID RENAME TO USER_ID_DEPRECATED;

CREATE DOMAIN USER_ID AS VARCHAR(256);


ALTER TABLE IF EXISTS PERSONS
    ALTER COLUMN FIRST_NAME TYPE TEXT,
    ALTER COLUMN LAST_NAME TYPE TEXT,
    ALTER COLUMN EMAIL TYPE EMAIL_VALUE,
    ALTER COLUMN USER_ID TYPE USER_ID;

DROP DOMAIN IF EXISTS USER_ID_DEPRECATED;

    