ALTER TABLE SAMPLE_PROPERTIES DROP CONSTRAINT SAMPLE_PROPERTIES_UNIQUE_FK;
ALTER TABLE SAMPLE_PROPERTIES ADD CONSTRAINT SAMPLE_PROPERTIES_UNIQUE_FK FOREIGN KEY (STPT_ID, IS_UNIQUE) REFERENCES SAMPLE_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE) ON DELETE CASCADE;
ALTER TABLE EXPERIMENT_PROPERTIES DROP CONSTRAINT EXPERIMENT_PROPERTIES_UNIQUE_FK;
ALTER TABLE EXPERIMENT_PROPERTIES ADD CONSTRAINT EXPERIMENT_PROPERTIES_UNIQUE_FK FOREIGN KEY (ETPT_ID, IS_UNIQUE) REFERENCES EXPERIMENT_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE) ON DELETE CASCADE;
ALTER TABLE DATA_SET_PROPERTIES DROP CONSTRAINT DATA_SET_PROPERTIES_UNIQUE_FK;
ALTER TABLE DATA_SET_PROPERTIES ADD CONSTRAINT DATA_SET_PROPERTIES_UNIQUE_FK FOREIGN KEY (DSTPT_ID, IS_UNIQUE) REFERENCES DATA_SET_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE) ON DELETE CASCADE;
ALTER TABLE MATERIAL_PROPERTIES DROP CONSTRAINT MATERIAL_PROPERTIES_UNIQUE_FK;
ALTER TABLE MATERIAL_PROPERTIES ADD CONSTRAINT MATERIAL_PROPERTIES_UNIQUE_FK FOREIGN KEY (MTPT_ID, IS_UNIQUE) REFERENCES MATERIAL_TYPE_PROPERTY_TYPES(ID, IS_UNIQUE) ON DELETE CASCADE;