const ALL_COLUMNS = 'ALL_COLUMNS'
const VISIBLE_COLUMNS = 'VISIBLE_COLUMNS'
const ALL_PAGES = 'ALL_PAGES'
const CURRENT_PAGE = 'CURRENT_PAGE'
const SELECTED_ROWS = 'SELECTED_ROWS'
const PLAIN_TEXT = 'PLAIN_TEXT'
const RICH_TEXT = 'RICH_TEXT'

export default {
  ALL_COLUMNS,
  VISIBLE_COLUMNS,
  ALL_PAGES,
  CURRENT_PAGE,
  SELECTED_ROWS,
  PLAIN_TEXT,
  RICH_TEXT
}
