const COLUMN_FILTERS = 'COLUMN_FILTERS'
const GLOBAL_FILTER = 'GLOBAL_FILTER'
const FILTER_MODE_OPTIONS = [COLUMN_FILTERS, GLOBAL_FILTER]

export default {
  COLUMN_FILTERS,
  GLOBAL_FILTER,
  FILTER_MODE_OPTIONS
}
