package ch.ethz.sis.openbis.generic.server.xls.importxls.helper;

import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.id.EntityTypePermId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.plugin.id.PluginPermId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.create.SampleTypeCreation;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.fetchoptions.SampleTypeFetchOptions;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.update.SampleTypeUpdate;
import ch.ethz.sis.openbis.generic.server.xls.importxls.delay.DelayedExecutionDecorator;
import ch.ethz.sis.openbis.generic.server.xls.importxls.enums.ImportModes;
import ch.ethz.sis.openbis.generic.server.xls.importxls.enums.ImportTypes;
import ch.ethz.sis.openbis.generic.server.xls.importxls.utils.ImportUtils;
import ch.ethz.sis.openbis.generic.server.xls.importxls.utils.VersionUtils;

import java.util.List;
import java.util.Locale;
import java.util.Map;

public class SampleTypeImportHelper extends BasicImportHelper
{
    private final DelayedExecutionDecorator delayedExecutor;

    private final Map<String, Integer> versions;

    public SampleTypeImportHelper(DelayedExecutionDecorator delayedExecutor, ImportModes mode, Map<String, Integer> versions)
    {
        super(mode);
        this.versions = versions;
        this.delayedExecutor = delayedExecutor;
    }

    @Override protected String getTypeName()
    {
        return "sample type";
    }

    @Override protected boolean isNewVersion(Map<String, Integer> header, List<String> values)
    {
        String version = getValueByColumnName(header, values, "version");
        String code = getValueByColumnName(header, values, "code");

        return VersionUtils.isNewVersion(version, VersionUtils.getStoredVersion(versions, ImportTypes.SAMPLE_TYPE.getType(), code));
    }

    @Override protected void updateVersion(Map<String, Integer> header, List<String> values)
    {
        String version = getValueByColumnName(header, values, "version");
        String code = getValueByColumnName(header, values, "code");

        VersionUtils.updateVersion(version, versions, ImportTypes.SAMPLE_TYPE.getType(), code);
    }

    @Override protected boolean isObjectExist(Map<String, Integer> header, List<String> values)
    {
        String code = getValueByColumnName(header, values, "code");
        EntityTypePermId id = new EntityTypePermId(code);

        return delayedExecutor.getSampleType(id, new SampleTypeFetchOptions()) != null;
    }

    @Override protected void createObject(Map<String, Integer> header, List<String> values, int page, int line)
    {
        String code = getValueByColumnName(header, values, "code");
        String description = getValueByColumnName(header, values, "description");
        String script = getValueByColumnName(header, values, "validation script");
        String autoGenerateCode = getValueByColumnName(header, values, "auto generate codes");
        String generatedCodePrefix = getValueByColumnName(header, values, "generated code prefix");

        SampleTypeCreation creation = new SampleTypeCreation();

        creation.setCode(code);
        creation.setDescription(description);
        creation.setAutoGeneratedCode(Boolean.parseBoolean(autoGenerateCode));
        if (script != null && !script.isEmpty())
        {
            creation.setValidationPluginId(new PluginPermId(ImportUtils.getScriptName(creation.getCode(), script)));
        }
        if (generatedCodePrefix != null && !generatedCodePrefix.isEmpty())
        {
            creation.setGeneratedCodePrefix(generatedCodePrefix);
        }

        delayedExecutor.createSampleType(creation, page, line);
    }

    @Override protected void updateObject(Map<String, Integer> header, List<String> values, int page, int line)
    {
        String code = getValueByColumnName(header, values, "code");
        String description = getValueByColumnName(header, values, "description");
        String script = getValueByColumnName(header, values, "validation script");
        String autoGenerateCode = getValueByColumnName(header, values, "auto generate codes");
        String generatedCodePrefix = getValueByColumnName(header, values, "generated code prefix");

        SampleTypeUpdate update = new SampleTypeUpdate();
        EntityTypePermId permId = new EntityTypePermId(code);
        update.setTypeId(permId);
        update.setDescription(description);
        update.setAutoGeneratedCode(Boolean.parseBoolean(autoGenerateCode));
        if (script != null && !script.isEmpty())
        {
            update.setValidationPluginId(new PluginPermId(ImportUtils.getScriptName(code, script)));
        }
        if (generatedCodePrefix != null && !generatedCodePrefix.isEmpty())
        {
            update.setGeneratedCodePrefix(generatedCodePrefix);
        }

        delayedExecutor.updateSampleType(update, page, line);
    }

    @Override protected void validateHeader(Map<String, Integer> header)
    {
        checkKeyExistence(header, "version");
        checkKeyExistence(header, "code");
        checkKeyExistence(header, "auto generate codes");
    }
}
