package ch.ethz.sis.openbis.generic.server.xls.importxls.helper;

import ch.ethz.sis.openbis.generic.asapi.v3.dto.entitytype.id.EntityTypePermId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.experiment.id.ExperimentIdentifier;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.project.id.ProjectIdentifier;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.property.PropertyType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.Sample;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.SampleType;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.create.SampleCreation;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.fetchoptions.SampleFetchOptions;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.fetchoptions.SampleTypeFetchOptions;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.id.ISampleId;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.id.SampleIdentifier;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.sample.update.SampleUpdate;
import ch.ethz.sis.openbis.generic.asapi.v3.dto.space.id.SpacePermId;
import ch.ethz.sis.openbis.generic.server.xls.importxls.ImportOptions;
import ch.ethz.sis.openbis.generic.server.xls.importxls.delay.DelayedExecutionDecorator;
import ch.ethz.sis.openbis.generic.server.xls.importxls.delay.IdentifierVariable;
import ch.ethz.sis.openbis.generic.server.xls.importxls.enums.ImportModes;
import ch.ethz.sis.openbis.generic.server.xls.importxls.utils.ImportUtils;
import ch.ethz.sis.openbis.generic.server.xls.importxls.utils.PropertyTypeSearcher;
import ch.systemsx.cisd.common.exceptions.UserFailureException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static ch.ethz.sis.openbis.generic.server.xls.importxls.utils.PropertyTypeSearcher.getPropertyValue;

public class SampleImportHelper extends BasicImportHelper
{
    private EntityTypePermId sampleType;

    private final ImportOptions options;

    private final DelayedExecutionDecorator delayedExecutor;

    private PropertyTypeSearcher propertyTypeSearcher;

    private static final HashSet<String> sampleAttributes = new HashSet<>(Arrays.asList("$", "identifier", "code", "space", "project",
            "experiment", "auto generate code", "parents", "children"));

    public SampleImportHelper(DelayedExecutionDecorator delayedExecutor, ImportModes mode, ImportOptions options)
    {
        super(mode);
        this.options = options;
        this.delayedExecutor = delayedExecutor;
    }

    @Override public void importBlock(List<List<String>> page, int pageIndex, int start, int end)
    {
        int lineIndex = start;

        try
        {
            Map<String, Integer> header = parseHeader(page.get(lineIndex), false);
            lineIndex++;

            sampleType = new EntityTypePermId(getValueByColumnName(header, page.get(lineIndex), "sample type"));

            // first check that sample type exist.
            SampleTypeFetchOptions fetchTypeOptions = new SampleTypeFetchOptions();
            fetchTypeOptions.withPropertyAssignments().withPropertyType().withVocabulary().withTerms();
            SampleType type = delayedExecutor.getSampleType(sampleType, fetchTypeOptions);
            if (type == null)
            {
                throw new UserFailureException("Sample type " + sampleType + " is not exist.");
            }
            this.propertyTypeSearcher = new PropertyTypeSearcher(type.getPropertyAssignments());

            lineIndex++;
        } catch (Exception e)
        {
            throw new UserFailureException("Exception at page " + pageIndex + " and line " + lineIndex + " with message: " + e.getMessage());
        }

        // and then import samples
        super.importBlock(page, pageIndex, start + 2, end);
    }

    @Override protected String getTypeName()
    {
        return "sample";
    }

    @Override protected boolean isObjectExist(Map<String, Integer> header, List<String> values)
    {
        SampleFetchOptions fetchOptions = new SampleFetchOptions();
        fetchOptions.withType();
        fetchOptions.withChildren();
        fetchOptions.withParents();
        fetchOptions.withProperties();

        String code = getValueByColumnName(header, values, "code");
        String space = getValueByColumnName(header, values, "space");
        String project = getValueByColumnName(header, values, "project");
        ISampleId sampleId = ImportUtils.buildSampleIdentifier(code, space, project);

        if (sampleId == null) // If sample codes are autogenerated they can't be known at the time of the creation. Is then a creation.
        {
            return false;
        } else
        {
            return delayedExecutor.getSample(sampleId, fetchOptions) != null;
        }
    }

    @Override protected void createObject(Map<String, Integer> header, List<String> values, int page, int line)
    {
        SampleCreation creation = new SampleCreation();
        creation.setTypeId(sampleType);

        String code = getValueByColumnName(header, values, "code");
        String variable = getValueByColumnName(header, values, "$");
        String autoGenerateCode = getValueByColumnName(header, values, "auto generate code");
        String space = getValueByColumnName(header, values, "space");
        String project = getValueByColumnName(header, values, "project");
        String experiment = getValueByColumnName(header, values, "experiment");
        String parents = getValueByColumnName(header, values, "parents");
        String children = getValueByColumnName(header, values, "children");

        if (options.getDisallowEntityCreations())
        {
            throw new UserFailureException("Entity creations disallowed but found at line: " + line + " [" + getTypeName() + "]");
        }

        if (code != null && !code.isEmpty())
        {
            creation.setCode(ImportUtils.valueNormalizer("code", code, false));
        }
        if (autoGenerateCode != null && !autoGenerateCode.isEmpty())
        {
            creation.setAutoGeneratedCode(Boolean.parseBoolean(autoGenerateCode));
        }
        if (space != null && !space.isEmpty())
        {
            creation.setSpaceId(new SpacePermId(ImportUtils.valueNormalizer("space", space, false)));
        }
        if (project != null && !project.isEmpty() && options.getAllowProjectSamples()) // Projects can only be set in project samples are enabled
        {
            creation.setProjectId(new ProjectIdentifier(ImportUtils.projectIdentifierNormalizer(project)));
        }
        if (experiment != null && !experiment.isEmpty())
        {
            creation.setExperimentId(new ExperimentIdentifier(ImportUtils.experimentIdentifierNormalizer(experiment)));
        }
        injectOwner(creation);
        if (parents != null && !parents.isEmpty())
        {
            List<ISampleId> parentIds = new ArrayList<>();
            for (String parent : parents.split("\n"))
            {
                if (parent.startsWith("$"))
                {
                    parentIds.add(new IdentifierVariable(parent));
                } else
                {
                    parentIds.add(new SampleIdentifier(parent));
                }
            }
            creation.setParentIds(parentIds);
        }
        if (children != null && !children.isEmpty())
        {
            List<ISampleId> childrenIds = new ArrayList<>();
            for (String child : children.split("\n"))
            {
                if (child.startsWith("$"))
                {
                    childrenIds.add(new IdentifierVariable(child));
                } else
                {
                    childrenIds.add(new SampleIdentifier(child));
                }
            }
            creation.setChildIds(childrenIds);
        }

        for (String key : header.keySet())
        {
            if (!sampleAttributes.contains(key))
            {
                String value = getValueByColumnName(header, values, key);
                PropertyType propertyType = propertyTypeSearcher.findPropertyType(key);
                creation.setProperty(propertyType.getCode(), getPropertyValue(propertyType, value));
            }
        }

        delayedExecutor.createSample(variable, creation, page, line);
    }

    @Override protected void updateObject(Map<String, Integer> header, List<String> values, int page, int line)
    {
        String code = getValueByColumnName(header, values, "code");
        String variable = getValueByColumnName(header, values, "$");
        String space = getValueByColumnName(header, values, "space");
        String project = getValueByColumnName(header, values, "project");
        String experiment = getValueByColumnName(header, values, "experiment");
        String parents = getValueByColumnName(header, values, "parents");
        String children = getValueByColumnName(header, values, "children");

        ISampleId sampleId = ImportUtils.buildSampleIdentifier(code, space, project);

        SampleFetchOptions fetchOptions = new SampleFetchOptions();
        fetchOptions.withChildren();
        fetchOptions.withParents();

        Sample originSample = delayedExecutor.getSample(sampleId, fetchOptions);

        SampleUpdate update = new SampleUpdate();
        update.setSampleId(sampleId);

        if (space != null && !space.isEmpty())
        {
            String normalizedSpace = ImportUtils.valueNormalizer("space", space, false);
            update.setSpaceId(new SpacePermId(normalizedSpace));
        }
        if (project != null && !project.isEmpty())
        {
            update.setProjectId(new ProjectIdentifier(ImportUtils.projectIdentifierNormalizer(project)));
        }
        if (experiment != null && !experiment.isEmpty())
        {
            update.setExperimentId(new ExperimentIdentifier(ImportUtils.experimentIdentifierNormalizer(experiment)));
        }

        Set<SampleIdentifier> parentIds = new HashSet<>();
        if (parents != null && !parents.isEmpty())
        {
            for (String parent : parents.split("\n"))
            {
                SampleIdentifier parentId = new SampleIdentifier(parent);
                update.getParentIds().add(parentId);
                parentIds.add(parentId);
            }
        }
        for (Sample parent : originSample.getParents())
        {
            if (!parentIds.contains(parent.getIdentifier()))
            {
                update.getParentIds().remove(parent.getIdentifier());
            }
        }
        Set<SampleIdentifier> childrenIds = new HashSet<>();
        if (children != null && !children.isEmpty())
        {
            for (String child : children.split("\n"))
            {
                SampleIdentifier childId = new SampleIdentifier(child);
                update.getChildIds().add(childId);
                childrenIds.add(childId);
            }
        }
        for (Sample child : originSample.getChildren())
        {
            if (!childrenIds.contains(child.getIdentifier()))
            {
                update.getChildIds().remove(child.getIdentifier());
            }
        }

        for (String key : header.keySet())
        {
            if (!sampleAttributes.contains(key))
            {
                String value = getValueByColumnName(header, values, key);
                if (value != null && (value.equals("--DELETE--") || value.equals("__DELETE__")))
                {
                    value = null;
                }
                PropertyType propertyType = propertyTypeSearcher.findPropertyType(key);
                update.setProperty(propertyType.getCode(), getPropertyValue(propertyType, value));
            }
        }

        delayedExecutor.updateSample(variable, update, page, line);
    }

    @Override protected void validateHeader(Map<String, Integer> header)
    {
        // nothing to validate
    }

    private void injectOwner(SampleCreation creation)
    {
        String typePermId = ((EntityTypePermId) creation.getTypeId()).getPermId();
        if (options.getExperimentsByType() != null &&
                options.getExperimentsByType().containsKey(typePermId) &&
                options.getExperimentsByType().get(typePermId) != null)
        {
            String experimentIdentifier = options.getExperimentsByType().get(typePermId);
            creation.setExperimentId(new ExperimentIdentifier(experimentIdentifier));
        }
        if (options.getSpacesByType() != null && options.getSpacesByType().containsKey(typePermId))
        {
            creation.setSpaceId(new SpacePermId(options.getSpacesByType().get(typePermId)));
        }
        if (creation.getExperimentId() != null && creation.getSpaceId() == null)
        {
            ExperimentIdentifier experimentIdentifier = (ExperimentIdentifier) creation.getExperimentId();
            creation.setSpaceId(new SpacePermId(experimentIdentifier.getIdentifier().split("/")[1]));
        }
        if (creation.getProjectId() != null && creation.getSpaceId() == null)
        {
            ProjectIdentifier projectIdentifier = (ProjectIdentifier) creation.getProjectId();
            creation.setSpaceId(new SpacePermId(projectIdentifier.getIdentifier().split("/")[1]));
        }
    }
}
